---
- name: Clone drivesync util to /opt/drivesync
  ansible.builtin.git:
    repo: "https://github.com/MStadlmeier/drivesync.git"
    dest: /opt/drivesync
  become: yes

- name: Create drivesync config folder
  ansible.builtin.file:
    path: "~/.drivesync"
    state: directory

- name: Symlink drivesync config
  ansible.builtin.file:
    src: "{{ role_path }}/files/drivesync.yml"
    dest: "~/.drivesync/config.yml"
    state: link

- name: Enable and start cronie
  ansible.builtin.systemd:
    name: cronie
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Ensure Documents exists
  ansible.builtin.file:
    path: "~/Documents"
    state: directory

- name: Ensure drivesync destination exists
  ansible.builtin.file:
    path: "~/Documents/drive"
    state: directory

- name: Symlink drivesync script
  ansible.builtin.file:
    src: "{{ role_path }}/files/drivesync"
    dest: "/usr/local/bin/drivesync"
    state: link
  become: yes

- name: Enable drivesync cronjob
  ansible.builtin.cron:
    name: "drivesync sync"
    minute: "*/2"
    job: "/usr/local/bin/drivesync sync"
  changed_when: true
  notify:
    - memo-drivesync
