---
- name: symlink vimrc
  file:
    src: "{{role_path}}/files/vimrc"
    dest: "~/.vimrc"
    state: link

- name: create vim/autoload
  file:
    dest: "~/.vim/autoload"
    state: directory

- name: symlink vim files
  file:
    src: "{{role_path}}/files/plug.vim"
    dest: "~/.vim/autoload/plug.vim"
    state: link

- name: global gitignore
  file:
    src: "~/git/config/.gitignore"
    dest: "~/.gitignore_global"
    state: link
