---
- include: dependencies.yml

- name: create nvim config
  file:
    dest: ~/.config/nvim
    state: directory

- name: create vim/autoload
  file:
    dest: "~/.config/nvim/autoload"
    state: directory

- name: symlink init.vim
  file:
    src: "{{role_path}}/files/init.vim"
    dest: "~/.config/nvim/init.vim"
    state: link

- name: symlink ginit.vim
  file:
    src: "{{role_path}}/files/ginit.vim"
    dest: "~/.config/nvim/ginit.vim"
    state: link

- name: symlink plug
  file:
    src: "{{role_path}}/files/plug.vim"
    dest: "~/.config/nvim/autoload/plug.vim"
    state: link

- name: global gitignore
  file:
    src: "~/git/config/.gitignore"
    dest: "~/.gitignore_global"
    state: link
