---
- name: symlink vimrc
  file:
    src: ".vimrc"
    dest: "~/.vimrc"
    state: link

- name: create vim/autoload
  file:
    dest: "~/.vim/autoload"
    state: directory

- name: symlink vim files
  file:
    src: "plug.vim"
    dest: "~/.vim/autoload/plug.vim"
    state: link

