---
- name: symlink zshrc
  file:
    src: "{{role_path}}/files/zshrc"
    dest: "~/.zshrc"
    state: link

- name: symlink zsh_aliases
  file:
    src: "{{role_path}}/files/zsh_aliases"
    dest: "~/.zsh_aliases"
    state: link
