---
- name: symlink zshrc
  file:
    src: "{{role_path}}/files/zshrc"
    dest: "~/.zshrc"
    state: link

- name: symlink zsh_aliases
  file:
    src: "{{role_path}}/files/zsh_aliases"
    dest: "~/.zsh_aliases"
    state: link

- name: symlink gitconfig
  file:
    src: "{{role_path}}/files/gitconfig"
    dest: "~/.gitconfig"
    state: link

- name: symlink xresources
  file:
    src: "{{role_path}}/files/Xresources"
    dest: "~/.Xresources"
    state: link

- name: symlink tmux.conf
  file:
    src: "{{role_path}}/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link
