---
- include: dependencies.yml

- name: symlink zshrc
  file:
    src: "{{role_path}}/files/zshrc"
    dest: "~/.zshrc"
    state: link

- name: symlink zsh_aliases
  file:
    src: "{{role_path}}/files/zsh_aliases"
    dest: "~/.zsh_aliases"
    state: link

- name: create fish config dif
  file:
    dest: "~/.config/fish"
    state: directory

- name: symlink fish config
  file:
    src: "{{role_path}}/files/config.fish"
    dest: "~/.config/fish/config.fish"
    state: link

- name: symlink fish functions folder
  file:
    src: "{{role_path}}/files/functions"
    dest: "~/.config/fish/functions"
    state: link

- name: symlink fish powershell config
  file:
    src: "{{role_path}}/files/powerline-shell.py"
    dest: "~/.config/fish/powerline-shell.py"
    state: link

- name: symlink gitconfig
  file:
    src: "{{role_path}}/files/gitconfig"
    dest: "~/.gitconfig"
    state: link

- name: symlink tmux.conf
  file:
    src: "{{role_path}}/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link

- name: symlink xresources
  file:
    src: "{{role_path}}/files/Xresources"
    dest: "~/.Xresources"
    state: link

- name: symlink pylintrc
  file:
    src: "{{role_path}}/files/pylintrc"
    dest: "~/.pylintrc"
    state: link

- name: symlink script volume
  file:
    src: "{{role_path}}/files/{{item}}"
    dest: "/usr/local/bin/{{item}}"
    state: link
  with_items:
    - "toggle-mute"
    - "volume-down"
    - "volume-up"
  become: yes
