---
- name: installing i3
  pacman:
    name: i3-wm
    state: present
  become: true

- name: install i3status
  pacman:
    name: i3status
    state: present
  become: true

- name: install py3status
  pacman:
    name: py3status
    state: present
  become: true

- name: install xlock
  pacman:
    name: xlockmore
    state: present
  become: true

- name: Ensure ~/.config/i3 exists
  file:
    path: "~/.config/i3"
    state: directory

- name: Ensure ~/.config/i3status exists
  file:
    path: "~/.config/i3status"
    state: directory

- name: installing dmenu
  pacman:
    name: dmenu
    state: present
  become: true

- name: copy i3 config
  file:
    src: "{{role_path}}/files/config"
    dest: "~/.config/i3/config"
    state: link

- name: copy i3status config
  file:
    src: "{{role_path}}/files/i3status-config"
    dest: "~/.config/i3status/config"
    state: link
