---
- name: installing i3
  pacman:
    name: i3
    state: present

- name: installing dmenu
  pacman:
    name: dmenu
    state: present

- name: copy i3 config
  file:
    src: "{{role_path}}/files/i3config"
    dest: "~/.config/i3/config"
    state: link
