---
- name: installing i3
  pacman:
    name: i3-wm
    state: present
  become: true

- name: install i3status
  pacman:
    name: i3status
    state: present
  become: true

- name: Ensure ~/.config/i3 exists
  file:
    path: "~/.config/i3"
    state: directory

- name: installing dmenu
  pacman:
    name: dmenu
    state: present
  become: true

- name: copy i3 config
  template:
    src: "i3config.j2"
    dest: "~/.config/i3/config"

- name: copy backlight script
  copy:
    src: "{{item}}"
    dest: "/usr/local/bin/{{item}}"
    mode: 0777
  become: true
  with_items:
    - backlight-down
    - backlight-up
  when: laptop
