---
- name: installing i3
  pacman:
    name: i3-wm
    state: present
  become: true

- name: install i3status
  pacman:
    name: i3status
    state: present
  become: true

- name: Ensure ~/.config/i3 exists
  file:
    path: "~/.config/i3"
    state: directory

- name: installing dmenu
  pacman:
    name: dmenu
    state: present
  become: true

- name: copy i3 config
  file:
    src: "{{role_path}}/files/config"
    dest: "~/.config/i3/config"
    state: link
