---
- name: "Base config"
  hosts: localhost
  pre_tasks:
    - name: create std config dir
      file:
        path: "~/.config"
        state: directory

  roles:
    - editor
    - utilities
    - xorg
    - i3
    - scripts
    - backup
