---
- name: "Base config"
  hosts: localhost
  pre_tasks:
    - name: update system
      pacman:
        update_cache: yes
        upgrade: yes
      become: true

  roles:
  - editor
  - utilities

